# Generated by Django 4.2.2 on 2023-06-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PCID',
            new_name='PCName',
        ),
    ]
